### ISSUE TITLE
[BUG] Can't select JPEG compression on OBS (Fedora 38 host)

### ISSUE THREAD

**Issue by midi1996** [YorVeX/xObsBeam#28]
**Describe the bug**
Cannot enable JPEC Compression entry in Bream Output Settings.

**To Reproduce**
1. Open Beam Output Settings
2. Check JPEG Compression

**Expected behavior**
JPEG Option enabled and sliders enabled

**Screenshots**
![image](https://github.com/YorVeX/xObsBeam/assets/4874726/01e99e17-efb2-43e5-a9c7-4d0e41e125e4)

https://github.com/YorVeX/xObsBeam/assets/4874726/9379721d-c813-43bd-a627-04e143ef2cca

**Logs and details about your system**
https://obsproject.com/logs/GL8OnCXK6vRE4ETQ

**Additional context**
- Using the RPMFusion build of obs, not flatpak.

**Comment by YorVeX** [comment]
Just a few hours ago I noticed a bug that the JPEG compression option is not properly hidden (as it should be) when the encoding library is not available. Which is the case for you according to your log:
![image](https://github.com/YorVeX/xObsBeam/assets/528974/ca227316-7086-4229-9d66-73471c8ae0cd)

Though for the sake of transparency and to avoid issue reports like this I am now thinking that maybe I should instead make it visible but show an explanation message when the library is not found.

Either way, you need to either compile that library yourself or find a package for your distribution, more information [here](https://github.com/YorVeX/xObsBeam/tree/main/libjpeg-turbo#linux). Let me know whether you have any trouble getting it to run, I didn't have so many Linux testers so far (that I know of), so I am happy about any feedback I can get.

**Comment by YorVeX** [comment]
In the next version the option for this case will stay visible but disabled and a warning text will be shown:
![image](https://github.com/YorVeX/xObsBeam/assets/528974/4850f170-42ba-47a0-9689-ffa0a97fd960)

The button will open the link from my comment above.
