### ISSUE TITLE
Add Indonesia translation

### ISSUE THREAD

**Issue by hapnan** [YorVeX/xObsBeam#29]
adding translation indonesia
[id-ID.ini](https://render.hapnanarsad.workers.dev/id-ID.ini)

**Comment by YorVeX** [comment]
> adding translation indonesia [id-ID.ini](https://render.hapnanarsad.workers.dev/id-ID.ini)

Thanks a lot, will be in the next release (hopefully the 1.0 release if no more bugs are found)!
