### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SirColeslaw** [YorVeX/xObsBeam#31]
**Describe the bug**
Installation cancels with error message.

**To Reproduce**
1. Start installation. <- Even tried to "Start as Administrator"
2. Define installation path (in my case other than default).
3. Get error message.
4. Tried on the other PC also, error stays the same.

**Expected behavior**
Installation finishes without errors.

**Screenshots**
![Screenshot 2024-02-03 075907](https://github.com/YorVeX/xObsBeam/assets/45994510/72b82475-2b7c-4564-acde-0adeddd90c3d)

Screenshot message translated:
"Error overwriting the file: ..."

**Logs and details about your system**

 - Windows 11 Pro 23H2 <- Using local administrator account
 - OBS 30.0.2 <- In portable mode, not installed in default folder.
 - Beam 1.0.0 <- Installer

**Comment by YorVeX** [comment]
The installer isn't intended to be used with a portable mode OBS.

It doesn't really make sense when you think about it, the idea of a portable folder being that you can just throw it anywhere and run it without installation, including through USB stick on a different PC, and then you'd have a plugin inside this folder that registers itself in the system for being installed in this fixed location.

For example, what is supposed to happen if you move the folder (including the plugin inside it) and then try to uninstall the plugin? And if you move the folder to a new PC, you still have the files in there, but no installation anyway, so PC 1 would have the Beam plugin properly installed and registered in the system to be in that folder, but on PC 2 for the same folder structure that's not the case. It goes on, when you use portable mode to be able to easily backup and recover that folder anytime, installation information would also be gone after recovery - or you recover an old folder from before installing it, then you system thinks the plugin is installed but it's not in the folder.

I guess that's just a long way of saying the two concepts "installer" and "portable" don't match 😄 

That's what the xObsBeam-win-x64.7z file is meant for, just unpack this into the portable OBS directory. And if you ever need to remove the plugin again, just check what is in that .7z file (it's not much) and delete the files manually.

**Comment by SirColeslaw** [comment]
Yeah, totally right. Thanks for pointing it out. Seems "bug" was a layer 8 problem ;)

Closed.
